- name: Update package cache and install rootless container prerequisites
  block:
    - name: Refresh the APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install the uidmap prerequisite for rootless containerd
      ansible.builtin.apt:
        name: "uidmap"
        state: present

- name: Run the containerd nerdctl rootless setup tool
  become: false
  ansible.builtin.command: " {{ temporary_folder }}/nerdctl/bin/containerd-rootless-setuptool.sh install"
  changed_when: true

- name: Create a docker symlink pointing to the nerdctl binary
  become: true
  ansible.builtin.file:
    src: "{{ install_path }}/nerdctl"
    dest: "{{ install_path }}/docker"
    state: link
    force: true
    mode: "0777"
