- name: Prepare temporary directory for containerd nerdctl installation
  ansible.builtin.include_tasks: 0-setup_temporary_folder.yaml

- name: Download the containerd nerdctl release tarball
  ansible.builtin.include_tasks: 1-download_files.yaml

- name: Extract the containerd nerdctl release archive
  ansible.builtin.include_tasks: 2-extract_files.yaml

- name: Install containerd nerdctl binaries to the target path
  ansible.builtin.include_tasks: 3-copy_files.yaml

- name: Update package cache and install rootless container prerequisites
  ansible.builtin.include_tasks: 4-post_install.yaml

- name: Remove temporary files created during containerd nerdctl installation
  ansible.builtin.include_tasks: 5-cleanup.yaml
