- name: Prepare containerd nerdctl temporary directory
  ansible.builtin.include_tasks: setup_temporary_folder.yaml

- name: Download containerd nerdctl release archive
  ansible.builtin.include_tasks: download_files.yaml

- name: Extract containerd nerdctl release archive
  ansible.builtin.include_tasks: extract_files.yaml

- name: Install containerd nerdctl binaries
  ansible.builtin.include_tasks: copy_files.yaml

- name: Configure containerd nerdctl post-installation settings
  ansible.builtin.include_tasks: post_install.yaml

- name: Remove temporary containerd nerdctl installation files
  ansible.builtin.include_tasks: cleanup.yaml
