- name: Extract nerdctl Archive
  block:
    - name: Create nerdctl Extraction Directory
      ansible.builtin.file:
        path: "{{ temporary_folder }}/nerdctl"
        state: directory
        mode: "0755"

    - name: Unarchive nerdctl Tarball
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/nerdctl.tar.gz"
        dest: "{{ temporary_folder }}/nerdctl"
        remote_src: true
        mode: "0755"
