- name: Setup nerdctl Temporary Directory
  ansible.builtin.include_tasks: setup_temporary_folder.yaml

- name: Download nerdctl Release
  ansible.builtin.include_tasks: download_files.yaml

- name: Extract nerdctl Release
  ansible.builtin.include_tasks: extract_files.yaml

- name: Copy nerdctl Binaries
  ansible.builtin.include_tasks: copy_files.yaml

- name: Post-Installation Setup for nerdctl
  ansible.builtin.include_tasks: post_install.yaml

- name: Cleanup nerdctl Temporary Files
  ansible.builtin.include_tasks: cleanup.yaml
