- name: Update Package Cache and Install Prerequisites
  block:
    - name: Update apt Package Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install uidmap Prerequisite
      ansible.builtin.apt:
        name: "uidmap"
        state: present

- name: Run nerdctl Rootless Setup Tool
  become: false
  ansible.builtin.command: " {{ temporary_folder }}/nerdctl/bin/containerd-rootless-setuptool.sh install"
  changed_when: true

- name: Create docker Symlink to nerdctl
  become: false
  ansible.builtin.file:
    src: "{{ install_path }}/nerdctl"
    dest: "{{ install_path }}/docker"
    state: link
    force: true
